# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fetch-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
# spec:
#   rules:
#   - host: my-fetch.com
#     http:
#       paths:
#       - path: /
#         pathType: Exact
#         backend:
#           service:
#             name: fetch-service
#             port: 
#               number: 80